name: Lab Connect Test

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "terraform/lab/**"]

jobs:
  test_connect:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform/lab
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Connect to Tailnet
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
          ping: ${{ vars.TAILNET_PING }}
      - name: Setup 1Password CLI
        uses: 1Password/install-cli-action@v4

      - name: Check connectivity
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          export PROXMOX_ENDPOINT=$(op read op://Homelab/proxmox-prod/endpoint)
          export PROXMOX_CREDENTIAL=$(op read op://Homelab/proxmox-prod/credential)

          curl --fail -v --show-error -k \
            -H "Authorization: PVEAPIToken=${PROXMOX_CREDENTIAL}" \
            "${PROXMOX_ENDPOINT%/}/api2/json/access/permissions"

          