name: Lab Plan

on:
  push:
    branches: [ "main" ]
    paths: [ "terraform/lab/**"]

jobs:
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform/lab
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.PLAN_ROLE_ARN }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15
      - name: Setup 1Password CLI
        uses: 1Password/install-cli-action@v4
      
      - name: Connect to Tailnet
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
          ping: ${{ vars.TAILNET_PING }}

      - name: Initialize Terraform
        env:
          TF_CLI_ARGS_init: -backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET }} -backend-config=key=lab/terraform.tfstate -backend-config=region=us-east-1
        run: terraform init

      - name: Run Terraform Apply
        id: apply
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          op run --env-file .env.tpl -- terraform apply -auto-approve